version: 2
updates:
  # Update Rust dependencies
   - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

   - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

   - package-ecosystem: "cargo"
    directory: "/db"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

   - package-ecosystem: "cargo"
    directory: "/services"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
